# Generated by Django 5.1.7 on 2025-04-13 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_maplocation_neighbourhood_location_zipcode_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="page.maplocation",
            ),
        ),
        migrations.AddField(
            model_name="zipcode",
            name="zip_code",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="zipcode",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="page.maplocation",
            ),
        ),
        migrations.AlterField(
            model_name="zipcode",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="page.region"
            ),
        ),
    ]
