# Generated by Django 5.1.7 on 2025-04-13 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_region_location_zipcode_zip_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zipcode",
            name="id",
        ),
        migrations.AlterField(
            model_name="zipcode",
            name="region",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="page.region",
            ),
        ),
    ]
