# Generated by Django 5.1.7 on 2025-04-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0004_remove_zipcode_id_alter_zipcode_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prices",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="prices",
            name="longitude",
        ),
    ]
