# Generated by Django 5.1.7 on 2025-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0005_remove_prices_latitude_remove_prices_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="num_bathrooms",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="num_bedrooms",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="review",
            name="ownership_status",
            field=models.CharField(
                choices=[("rent", "Rent"), ("own", "Own")], default="rent", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="price_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="review",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
